version: '3.9'

services:
  frontend:
    build:
      context: ./services/frontend
      dockerfile: dev.Dockerfile
    restart: always
    ports:
      - 8080:5173
    depends_on:
      - backend
    environment:
      - VITE_DB_ADDRESS=http://localhost:9090

  backend:
    build:
      context: ./services/backend
    restart: always
    ports:
      - 9090:9090
    env_file:
      - .env

# Only enable this if you want to use a local mongodb instance
  # db:  # This service name will be also used as hostname for MONGODB_URI
  #   image: mongo:7.0.2
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - mongodb-data:/data/db
    

# Only enable this if you want to use a local mongodb instance
# volumes:
#   mongodb-data:
